### ISSUE TITLE
Everybody should be subscribed to the organization

### ISSUE THREAD

**Issue by massimotisi** [CACAO2020/CACAO2020#14]
Everybody should be listed here: https://github.com/orgs/CACAO2020/teams

**Comment by massimotisi** [comment]
Missing:
- @MadRealm from @CACAO2020/eq3transformateur1 
- @LoicL971 and @n19abdal from @CACAO2020/eq4transformateur2

**Comment by massimotisi** [comment]
@QuentinAndre11 can you please ping the members of your group to get this done?

**Comment by QuentinAndre11** [comment]
I transmitted

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "CACAO2020/CACAO2020" <CACAO2020@noreply.github.com>
Cc: "QuentinAndre11" <quentin.andre@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Lundi 27 Avril 2020 14:45:27
Objet: Re: [CACAO2020/CACAO2020] Everybody should be subscribed to the organization (#14)

@QuentinAndre11 can you please ping the members of your group to get this done?
